# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: dataset.yaml
  - model: tab_rnn.yaml

# task name, determines output directory path
task_name: "compile"

monitor_metric: "val/gini_avg_best"

# simply provide checkpoint path to resume training
ckpt_path: "/home/danil/projects/torch_template/nfs/samples_RNN/LHT_credits-history/logs/train/runs/2024-03-30_23-16-50/checkpoints/epoch_003.ckpt"

# seed for random number generators in pytorch, numpy and python.random
seed: 7